# Returns the host triple.
# Invokes config.guess

function( get_host_triple var )
  if( MSVC )
    if( CMAKE_CL_64 )
      set( value "x86_64-pc-win32" )
    else()
      set( value "i686-pc-win32" )
    endif()
  elseif( CMAKE_SYSTEM_NAME STREQUAL "Emscripten" )
    set( value "wasm32-unknown-emscripten" )
  elseif( MINGW AND NOT MSYS )
    if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
      set( value "x86_64-w64-mingw32" )
    else()
      set( value "i686-pc-mingw32" )
    endif()
  elseif( CMAKE_HOST_WIN32 )
    string(TOLOWER "${CMAKE_HOST_SYSTEM_PROCESSOR}" _host_proc)
    if( _host_proc MATCHES "amd64|x86_64" )
      set( value "x86_64-pc-windows-msvc" )
    elseif( _host_proc MATCHES "arm64|aarch64" )
      set( value "aarch64-pc-windows-msvc" )
    else()
      set( value "i686-pc-windows-msvc" )
    endif()
  else( MSVC )
    set(config_guess ${LLVM_MAIN_SRC_DIR}/autoconf/config.guess)
    find_program(_host_sh NAMES sh)
    if( _host_sh AND EXISTS ${config_guess} )
      execute_process(COMMAND ${_host_sh} ${config_guess}
        RESULT_VARIABLE TT_RV
        OUTPUT_VARIABLE TT_OUT
        OUTPUT_STRIP_TRAILING_WHITESPACE)
      if( TT_RV EQUAL 0 )
        set( value ${TT_OUT} )
      else()
        message(FATAL_ERROR "Failed to execute ${config_guess}")
      endif()
    else()
      set( value "${CMAKE_HOST_SYSTEM_PROCESSOR}-unknown-${CMAKE_HOST_SYSTEM_NAME}" )
      string(TOLOWER "${value}" value)
    endif()
  endif( MSVC )
  set( ${var} ${value} PARENT_SCOPE )
  message(STATUS "Target triple: ${value}")
endfunction( get_host_triple var )
